### PR TITLE
Updated REQUIRE and a bunch of other things

### PR DESCRIPTION
**Pull request by mauro3**
In light of a new version for METADATA.

Optional (but I don't have the permissions):
- setup appveyor
- setup attobot: https://github.com/attobot/attobot

### CODE REVIEW

**Comment by nignatiadis** [comment]
Cool, thanks! Unless I messed up, I think appveyor and attobot should also be working now (let me know if not). Feel free to merge this whenever you want.

**Comment by mauro3** [comment]
Thanks. I'll update the README for the appveyor badge, see what it says and merge.

**Comment by mauro3** [comment]
I dropped Julia 0.4 support in the REQUIRE (although it still seems to work).  Is that ok?  If so I need to also update appveyor.yml to reflect this.

**Comment by nignatiadis** [comment]
Yes, of course it is ok!

**Comment by mauro3** [comment]
I'll merge after the CI run.

**Comment by mauro3** [comment]
Yep, attobot is running: https://github.com/JuliaLang/METADATA.jl/pull/7875

**Comment by nignatiadis** [comment]
Great, thank you for doing this!

**Pull request merged**
