### PR TITLE
0.7 compatibility

### PR DESCRIPTION
**Pull request by helgee**
Fix deprecations, drop old versions, and update CI.

It would be good to cut a new release soon so I can continue updating my dependent packages 👍

### CODE REVIEW

**Comment by mauro3** [comment]
Do you know what the Travis failures are about?

**Comment by helgee** [comment]
Not really. I would assume that this is a Pkg3 bug that has been ironed out already because the version resolution works on nightly.

**Comment by helgee** [comment]
From Slack:

> Helge Eichhorn [13:14 Uhr]
> I have updated SmoothingSpline.jl but for some reason the dependency resolution fails on 0.7 on Travis: https://travis-ci.org/nignatiadis/SmoothingSplines.jl/jobs/403492968#L467-L476
> It works fine on nightly. Is this a known issue?
> 
> Kristoffer Carlsson [13:16 Uhr]
> Yes
> A new beta should be out probably today
> 
> Helge Eichhorn [13:16 Uhr]
> Great :+1: So I can just ignore it and tag a release?
> 
> Kristoffer Carlsson [13:16 Uhr]
> So focus on nightly for now
> yes

**Comment by mauro3** [comment]
Thanks for digging this up!  

LGTM.  However, as Julia-0.6 support is dropped, I will leave the Boss (@nignatiadis) time over the weekend to comment on this.  Otherwise I'll merge and tag on Monday, I hope this is ok.  (ping me if I forget)

**Comment by helgee** [comment]
@mauro3 bump 😉

**Comment by nignatiadis** [comment]
Looks good to me too, thanks @helgee and @mauro3!

**Comment by mauro3** [comment]
Thanks @helgee!

**Pull request merged**
